# Generated by Django 4.1.3 on 2022-12-25 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multilevelapp.person')),
                ('email', models.EmailField(max_length=30)),
                ('mobile', models.BigIntegerField()),
            ],
            bases=('multilevelapp.person',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multilevelapp.student')),
                ('salary', models.FloatField()),
                ('company', models.CharField(max_length=30)),
                ('company_location', models.CharField(max_length=30)),
            ],
            bases=('multilevelapp.student',),
        ),
    ]
